# Generated by Django 4.1.7 on 2023-04-05 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='views_number',
            field=models.IntegerField(default=0),
        ),
    ]
