# Generated by Django 4.1.7 on 2023-04-05 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_viewnumber'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='ProductModel',
        ),
    ]
