# Generated by Django 4.1.7 on 2023-04-13 08:15

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0008_alter_commentmodel_options_favoritproductmodel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FavoritProductModel',
            new_name='FavoriteProductModel',
        ),
        migrations.AlterModelOptions(
            name='favoriteproductmodel',
            options={'verbose_name': 'Favorite', 'verbose_name_plural': 'Favorites'},
        ),
    ]
